services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    ports:
      - 4444:4444 # Selenium service
      - 5900:5900 # VNC server
      - 7900:7900 # VNC browser client
  firefox:
    image: selenium/standalone-firefox
    shm_size: '2gb'
    ports:
      - 4445:4444 # Selenium service
      - 5901:5900 # VNC server
      - 7901:7900 # VNC browser client
  node:
    image: node:22
    volumes:
      - ./:/project
    working_dir: /project
    tty: true